// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package openssl

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadOpenssl returns the embedded CollectionSpec for openssl.
func loadOpenssl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpensslBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load openssl: %w", err)
	}

	return spec, err
}

// loadOpensslObjects loads openssl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//     *opensslObjects
//     *opensslPrograms
//     *opensslMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpensslObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpenssl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// opensslSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensslSpecs struct {
	opensslProgramSpecs
	opensslMapSpecs
}

// opensslSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensslProgramSpecs struct {
	SSL_readwriteEnter *ebpf.ProgramSpec `ebpf:"SSL_readwrite_enter"`
	SSL_readwriteRet   *ebpf.ProgramSpec `ebpf:"SSL_readwrite_ret"`
}

// opensslMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensslMapSpecs struct {
	BufAddr *ebpf.MapSpec `ebpf:"buf_addr"`
	Events  *ebpf.MapSpec `ebpf:"events"`
}

// opensslObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpensslObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensslObjects struct {
	opensslPrograms
	opensslMaps
}

func (o *opensslObjects) Close() error {
	return _OpensslClose(
		&o.opensslPrograms,
		&o.opensslMaps,
	)
}

// opensslMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpensslObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensslMaps struct {
	BufAddr *ebpf.Map `ebpf:"buf_addr"`
	Events  *ebpf.Map `ebpf:"events"`
}

func (m *opensslMaps) Close() error {
	return _OpensslClose(
		m.BufAddr,
		m.Events,
	)
}

// opensslPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpensslObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensslPrograms struct {
	SSL_readwriteEnter *ebpf.Program `ebpf:"SSL_readwrite_enter"`
	SSL_readwriteRet   *ebpf.Program `ebpf:"SSL_readwrite_ret"`
}

func (p *opensslPrograms) Close() error {
	return _OpensslClose(
		p.SSL_readwriteEnter,
		p.SSL_readwriteRet,
	)
}

func _OpensslClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed openssl_bpfel.o
var _OpensslBytes []byte
